package com.deyvieat.smartstock.core.ui.theme

import androidx.compose.ui.graphics.Color

//Light
val primaryLight                    = Color(0xFF006A60)
val onPrimaryLight                  = Color(0xFFFFFFFF)
val primaryContainerLight           = Color(0xFF9EF2E4)
val onPrimaryContainerLight         = Color(0xFF00201C)
val secondaryLight                  = Color(0xFF4A635F)
val onSecondaryLight                = Color(0xFFFFFFFF)
val secondaryContainerLight         = Color(0xFFCCE8E3)
val onSecondaryContainerLight       = Color(0xFF05201C)
val tertiaryLight                   = Color(0xFF456179)
val onTertiaryLight                 = Color(0xFFFFFFFF)
val tertiaryContainerLight          = Color(0xFFCCE5FF)
val onTertiaryContainerLight        = Color(0xFF001E31)
val errorLight                      = Color(0xFFBA1A1A)
val onErrorLight                    = Color(0xFFFFFFFF)
val errorContainerLight             = Color(0xFFFFDAD6)
val onErrorContainerLight           = Color(0xFF410002)
val backgroundLight                 = Color(0xFFF4FBF8)
val onBackgroundLight               = Color(0xFF161D1B)
val surfaceLight                    = Color(0xFFF4FBF8)
val onSurfaceLight                  = Color(0xFF161D1B)
val surfaceVariantLight             = Color(0xFFDAE5E1)
val onSurfaceVariantLight           = Color(0xFF3F4946)
val outlineLight                    = Color(0xFF6F7976)
val outlineVariantLight             = Color(0xFFBEC9C6)
val scrimLight                      = Color(0xFF000000)
val inverseSurfaceLight             = Color(0xFF2B3230)
val inverseOnSurfaceLight           = Color(0xFFECF2EF)
val inversePrimaryLight             = Color(0xFF82D5CA)
val surfaceDimLight                 = Color(0xFFD5DBD9)
val surfaceBrightLight              = Color(0xFFF4FBF8)
val surfaceContainerLowestLight     = Color(0xFFFFFFFF)
val surfaceContainerLowLight        = Color(0xFFEFF5F2)
val surfaceContainerLight           = Color(0xFFE9EFEC)
val surfaceContainerHighLight       = Color(0xFFE3EAE7)
val surfaceContainerHighestLight    = Color(0xFFDDE4E1)

//Dark
val primaryDark                     = Color(0xFF82D5CA)
val onPrimaryDark                   = Color(0xFF003731)
val primaryContainerDark            = Color(0xFF004F47)
val onPrimaryContainerDark          = Color(0xFF9EF2E4)
val secondaryDark                   = Color(0xFFB1CCCA)
val onSecondaryDark                 = Color(0xFF1C3532)
val secondaryContainerDark          = Color(0xFF334B48)
val onSecondaryContainerDark        = Color(0xFFCCE8E3)
val tertiaryDark                    = Color(0xFFADC9E4)
val onTertiaryDark                  = Color(0xFF153349)
val tertiaryContainerDark           = Color(0xFF2D4961)
val onTertiaryContainerDark         = Color(0xFFCCE5FF)
val errorDark                       = Color(0xFFFFB4AB)
val onErrorDark                     = Color(0xFF690005)
val errorContainerDark              = Color(0xFF93000A)
val onErrorContainerDark            = Color(0xFFFFDAD6)
val backgroundDark                  = Color(0xFF0E1513)
val onBackgroundDark                = Color(0xFFDCE4E1)
val surfaceDark                     = Color(0xFF0E1513)
val onSurfaceDark                   = Color(0xFFDCE4E1)
val surfaceVariantDark              = Color(0xFF3F4946)
val onSurfaceVariantDark            = Color(0xFFBEC9C6)
val outlineDark                     = Color(0xFF899390)
val outlineVariantDark              = Color(0xFF3F4946)
val scrimDark                       = Color(0xFF000000)
val inverseSurfaceDark              = Color(0xFFDCE4E1)
val inverseOnSurfaceDark            = Color(0xFF2B3230)
val inversePrimaryDark              = Color(0xFF006A60)
val surfaceDimDark                  = Color(0xFF0E1513)
val surfaceBrightDark               = Color(0xFF343B39)
val surfaceContainerLowestDark      = Color(0xFF090F0E)
val surfaceContainerLowDark         = Color(0xFF161D1B)
val surfaceContainerDark            = Color(0xFF1A2120)
val surfaceContainerHighDark        = Color(0xFF252C2A)
val surfaceContainerHighestDark     = Color(0xFF303735)
